### PR TITLE
Please review my files 

### PR DESCRIPTION
**Pull request by camerrg**
I created the new-list jsp.  I don't think that you can see here.  I have copied it for you to review. 
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Create a new list</title>
</head>
<body>
<form action = "createNewListServlet" method="post">
Animal Name: <input type ="text" name = "animalType"><br />
Trip date: <input type ="text" name = "month" placeholder="mm"
size="4"> <input type ="text" name = "day" placeholder="dd"
size="4">, <input type ="text" name = "year" placeholder="yyyy"
size="4">
Animal: <input type = "text" name = "animalType"><br />
Available Location:<br />
<select name="allLocationToAdd" multiple size="6">
<c:forEach items="${requestScope.allItems}" var="currentitem">
 <option value = "${currentattractions.id}">${currentattractions.location}</option>
</c:forEach>
</select>
<br />
<input type = "submit" value="Create List and Add Items">
</form>
<a href = "index.html">Go add new items instead.</a>
</body>
</html>

### CODE REVIEW

**Review by jakuberski — APPROVED** [review]

**Review by jakuberski — APPROVED** [review]

**Comment by jakuberski** [comment]
Looks good!

**Review by jakuberski — APPROVED** [review]

**Review by jakuberski — APPROVED** [review]

**Review by camerrg — COMMENTED** [review]
Looks good.

**Review by camerrg — COMMENTED** [review]
Looks good

**Review by camerrg — COMMENTED** [review]
Looks good committing

**Pull request closed without merging**
